### PR TITLE
remove use of deprecated apis and fixed bugs around the output skeleton overwriting the input skeleton.

### PR DESCRIPTION
**Pull request by creadmefford**
not sure how to handle the const_cast though.

### CODE REVIEW

**Comment by paroj** [comment]
I tested meshmerge with current master using the bundled athene.mesh and knot.mesh,

```
meshmagick meshmerge athene.mesh knot.mesh -- test.mesh
```
which gave me this [test.zip](https://github.com/OGRECave/meshmagick/files/4697667/test.zip)

screenshot_test_20200528_210453558

If your result is different, your change probably broke it.

Also, what exactly is preventing compilation with the deprecated APIs for you?

**Comment by creadmefford** [comment]
great, i can convert these successfully with the changes.  the strange behavior i get on another two meshes happens exactly the same with or without my changes.  

i can compile everything fine with deprecated APIs.  i need to write some code similar to mesh magick and wanted to see if i could do it without using deprecated APIs though.  

accessing pose->getVertexOffsets() is the only potential issue if you need to change the offset values.  it looks like with the non-deprecated API your only option is to remove and add the vertexes back into the map.  you can't directly update the contents without a const_cast.

is the goal to remove the non-const versions of the API in order to refactor the internal data structures (eventually)?

**Comment by paroj** [comment]
> is the goal to remove the non-const versions of the API in order to refactor the internal data structures (eventually)?

no, I merely dropped it as it was not used internally. However after taking a closer look, it was a good idea as the non-const version did not invalidate the state. So any additions or changes after _getHardwareVertexBuffer would not be reflected.
This makes the offline tool usage the only valid one..

I will add a mutable `_getVertexOffsets` overload for this. Meanwhile the const cast should be fine.

**Comment by creadmefford** [comment]
great, thanks!

**Pull request merged**
